# Generated by Django 2.1.1 on 2018-11-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NBA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('conference', models.CharField(max_length=200, null=True)),
                ('date', models.CharField(max_length=200, null=True)),
                ('date_year', models.CharField(max_length=200, null=True)),
                ('date_date', models.CharField(max_length=200, null=True)),
                ('player', models.CharField(max_length=200, null=True)),
                ('position', models.CharField(max_length=200, null=True)),
                ('season', models.CharField(max_length=200, null=True)),
                ('season_short', models.CharField(max_length=200, null=True)),
                ('league', models.CharField(max_length=200, null=True)),
                ('team', models.CharField(max_length=200, null=True)),
                ('weight', models.CharField(max_length=200, null=True)),
                ('real_value', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
