# Generated by Django 2.1.1 on 2018-11-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yrj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nba',
            name='age',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
